---
title: "R 06"
output: html_notebook
---

# Comparison of means: two populations/samples

```{r}
setwd('/home/hieu/BDMA/SL/')
temp.data <- read.table('normtemp-data/normtemp.txt', head=T)
temp.data$temperature <- (temp.data$temperature-32)*5/9
attach(temp.data)
```

```{r}
# Histograms comparison
par(mfrow=c(1, 2))
hist(temperature[gender=='M'], main='Men', prob=T, col='yellow', xlab='body temperature')
hist(temperature[gender=='F'], main='Women', prob=T, col='yellow', xlab='body temperature')
par(mfrow=c(1, 1))

d.m <- density(temperature[gender=='M'])
d.f <- density(temperature[gender=='F'])
plot(d.m, main="", lwd=2, col='blue', ylim=c(0, 0.7))
lines(d.f, lwd=2, col='red')

# side-by-side boxplots
boxplot(temperature ~ gender, col='lightgray')
```

```{r}
# Normal quantile plots
par(mfrow=c(1,2))
qqnorm(temperature[gender=='M'], main="Males")
qqline(temperature[gender=='M'])

qqnorm(temperature[gender=='F'], main='Females')
qqline(temperature[gender=='F'])
par(mfrow=c(1,1))
```

```{r}
# Males
n1 <- length(temperature[gender=='M'])
n1

m.1 <- mean(temperature[gender=='M'])
m.1

s2.1 <- var(temperature[gender=='M'])
s2.1

# Females
n2 <- length(temperature[gender=='F'])
n2

m.2 <- mean(temperature[gender=='F'])
m.2

s2.2 <- var(temperature[gender=='F'])
s2.2

# pooled variance
pooled.var <- ((n1-1)*s2.1+(n2-1)*s2.2)/(n1+n2-2)

# test statistic
t.obs <- (m.1-m.2)/(sqrt(pooled.var*(1/n1 +1/n2)))
t.obs
p.value <- 2*pt(-abs(t.obs), n1+n2-2)
p.value
```

```{r}
# function t.test()
t.test(temperature[gender=='M'], temperature[gender=='F'], var.equal=TRUE)
t.test(temperature ~ gender, var.equal=TRUE)
```

Comparing variances

```{r}
# critical values
qf(0.025, n1-1, n2-1)
qf(0.975, n1-1, n2-1)

# observed value of the test statistics
t.obs <- s2.1/s2.2
t.obs

# compute the p.value
1/t.obs
p.value <- pf(t.obs, n1-1, n2-1)+ (1-pf(1/t.obs, n2-1,n1-1))
p.value

var.test(temperature[gender=='M'], temperature[gender=='F'])
var.test(temperature~gender)

# t.test non-equal variances
t.test(temperature ~ gender, var.equal=FALSE)
```

# Comparison of means for paired data

```{r}
data(sleep)
attach(sleep)
```

```{r}
g1 <- extra[group==1]
g2 <- extra[group==2]

d <- g2-g1
qqnorm(d)
qqline(d)

boxplot(g2-g1, col="lightgray")
abline(h=0, lty=2)

t.test(d)

# wrong application of the t-test 
t.test(g2, g1, paired=FALSE)

# t-test for paired data 
t.test(g2, g1, paired=TRUE)
t.test(d)
```

# Comparing proportions

```{r}
M <- matrix(c(335, 76, 302, 105), ncol=2, byrow=TRUE)
M
margin.table(M, margin=1)

# Placebo
n1 <- 335+76
pp.hat <- 335/n1
pp.hat

# Vitamin C
n2 <- 302+105
pc.hat <- 302/n2
pc.hat

# pooled pi
p.hat <- (335+302)/(n1+n2)
p.hat

se.hat <- sqrt(p.hat*(1-p.hat)*(1/n1+1/n2))
se.hat

t.obs <- (pp.hat-pc.hat)/se.hat
t.obs

p.value <- 1-pnorm(t.obs)
p.value

# binom.test
prop.test(c(335, 302), c(n1, n2), alt='g')
```
